"""empty message

Revision ID: 2a8373445ef2
Revises: fb660c4a6cfd
Create Date: 2022-08-25 17:13:35.100188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8373445ef2'
down_revision = 'fb660c4a6cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_vid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_vid')
    # ### end Alembic commands ###
