"""empty message

Revision ID: 9627e413a990
Revises: 2a8373445ef2
Create Date: 2022-08-26 20:28:11.468791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9627e413a990'
down_revision = '2a8373445ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_aud', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_aud')
    # ### end Alembic commands ###
