"""empty message

Revision ID: fb660c4a6cfd
Revises: 3648c041eb8c
Create Date: 2022-08-25 13:08:52.344802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb660c4a6cfd'
down_revision = '3648c041eb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_vid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_vid', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
